apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
        - name: superset
          image: saiakashb/superset-with-clickhouse:latest
          ports:
            - containerPort: 8088
          env:
            - name: SUPERSET_LOAD_EXAMPLES
              value: "no"
            - name: SUPERSET_SECRET_KEY
              value: "thisISaSECRET_1234"
            - name: DATABASE_URL
              value: "clickhouse://default:@clickhouse:9000/default"
          volumeMounts:
            - name: superset-storage
              mountPath: /var/lib/superset
          readinessProbe:
            httpGet:
              path: /
              port: 8088
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: superset-storage
          persistentVolumeClaim:
            claimName: superset-pvc
